CREATE TABLE IF NOT EXISTS `consultation` (
    `id` varchar(32) NOT NULL COMMENT '主键ID',
    `user_id` varchar(32) DEFAULT NULL COMMENT '患者ID',
    `doctor_id` varchar(32) DEFAULT NULL COMMENT '医生ID',
    `department_id` varchar(32) DEFAULT NULL COMMENT '科室ID',
    `appointment_id` varchar(32) DEFAULT NULL COMMENT '预约ID',
    `symptoms` text DEFAULT NULL COMMENT '症状描述',
    `diagnosis` text DEFAULT NULL COMMENT '诊断结果',
    `treatment` text DEFAULT NULL COMMENT '治疗方案',
    `status` varchar(20) DEFAULT NULL COMMENT '状态：PENDING-待就诊，IN_PROGRESS-就诊中，COMPLETED-已完成',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_doctor_id` (`doctor_id`),
    KEY `idx_department_id` (`department_id`),
    KEY `idx_appointment_id` (`appointment_id`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='问诊记录表'; 